### ISSUE TITLE
MTB00-Inception

### ISSUE THREAD

**Issue by glixius** [glixius/masterboard-api#1]
# MTB00 - Inception
Initial setup of a graphql server for masterboard app.

### Tasks
- [x] Add basic graphql usage.
- [x] Add code utilities.
- [x] Create an express based server with graphql.
- [x] Add Airtable connection to server.
- [x] Add environment behavior.
- [x] Add basic documentation.
- [x] Add basic testing behavior.
