### ISSUE TITLE
MTB01-GetLeagueInfo

### ISSUE THREAD

**Issue by glixius** [glixius/masterboard-api#3]
# MTB01 - Get League Info
Expose League related info through API.

### Tasks
- [x] Create Query types.
- [x] Create resolvers for every field.
- [x] Refactor code structure.
- [x] Add typescript.
- [x] Refactor Types from string to classes. (Documentation)
- [x] Add test to modified structure.
