### ISSUE TITLE
MTB02-GetCompetitors

### ISSUE THREAD

**Issue by glixius** [glixius/masterboard-api#5]
# MTB02 - Get Competitors
Expose Competitor related info through API.

### Tasks
- [x] Create query types.
- [x] Create controller & tests
- [x] Create competitor's airtable schema
- [x] Create adapter & tests
- [x] Create service & tests
- [x] Create entities & tests
