### ISSUE TITLE
MTB03-GetSportsInfo

### ISSUE THREAD

**Issue by glixius** [glixius/masterboard-api#7]
## MTB03 - Get Sports Info
Expose Sports related info through API.

### Tasks

- [x] Create sport entity & tests
- [x] Create sport format entity & tests
- [x] Create sports service & tests
- [x] Create sport formats service & tests
- [x] Create sports airtable schema
- [x] Create sport formats airtable schema
- [x] Create sports adapter & tests
- [x] Create sport formats adapter & tests
- [x] Create sports controller & tests
- [x] Create sport formats controller & tests
- [x] Create sports and sportFormats query types.
